### ISSUE TITLE
리액트 LV3 피드백 - 예병수 튜터

### ISSUE THREAD

**Issue by DevelopSoo** [hgyeom/Sparta_coding_club#2]
LV3를 구현하는데 다들 어려워하시는데 잘 구현하셨습니다.
고생하셨습니다.

추가적인 피드백은 아래에 작성하겠습니다.

**Comment by DevelopSoo** [comment]
현재는 하나의 레포지토리를 만들어 한 번에 다 넣고 있네요.
각 프로젝트마다 새로운 레포를 만들어야 합니다. 프로젝트 설치할 때 일일이 찾아야 해서 혼란스럽습니다. 또한 커밋도 다 섞여서 어떤 프로젝트의 커밋인지 확인할 수 없습니다.

다음 프로젝트땐 깃헙 레포지토리를 새로 만들어서 해주세요.

**Comment by DevelopSoo** [comment]
필수 구현 사항
<img width="751" alt="image" src="https://github.com/hgyeom/Sparta_coding_club/assets/69490984/b7fc799e-e052-4d8e-b898-5f8c59f78ae2">

실제 구현 사항
<img width="240" alt="스크린샷 2023-06-30 오후 5 59 13" src="https://github.com/hgyeom/Sparta_coding_club/assets/69490984/97207725-3e47-4c4b-9fb9-0d5b326a671f">

modal의 필수구현 사항에서는 두 모달 버튼을 다른 형태로 만드는 것이었습니다. 
다음엔 필수 구현 사항에 맞게 다르게 만들면 좋을 것 같습니다. 회사에서 필수 구현 사항 및 요청 사항과 다르게 개발을 할 경우 두 번 일하게 되는 불상사가 생깁니다. 다음엔 필수 구현 사항을 잘 파악해주시면 좋을 것 같습니다.

**Comment by DevelopSoo** [comment]
https://github.com/hgyeom/Sparta_coding_club/blob/1ee635bcb6a30cfae9fbc95ead68b4187b492d8c/solo/003.Input/web-prac/src/components/button/Buttons.jsx#L14-L16

아이콘을 넣는 곳에 일반 문자를 넣으셨네요. 다음 번엔 [React-icons](https://react-icons.github.io/react-icons/)와 같은 아이콘을 활용하는 것도 좋을 것 같습니다.

**Comment by DevelopSoo** [comment]
https://github.com/hgyeom/Sparta_coding_club/blob/1ee635bcb6a30cfae9fbc95ead68b4187b492d8c/solo/003.Input/web-prac/src/components/Modal/ModalControl.jsx#L46-L52

큰 문제는 되지 않지만 **mousedown 이벤트**를 쓰신 이유가 있을까요? **click 이벤트**가 있는데 굳이 **mousedown 이벤트**를 쓰신 이유가 궁금합니다. 

참고로 각 이벤트의 차이는 mousedown의 경우 마우스를 클릭하고 있는 상태 및 마우스 좌우 클릭 상관없이 발생하고, click 이벤트는 마우스 좌측을 클릭햇을 때 그리고 클릭 후 손을 땠을 때 발생합니다.

**Comment by DevelopSoo** [comment]
https://github.com/hgyeom/Sparta_coding_club/blob/1ee635bcb6a30cfae9fbc95ead68b4187b492d8c/solo/003.Input/web-prac/src/components/Modal/ModalControl.jsx#L31

ModalCotroll 에서 일반적인 단어가 아니라 오타가 발생했습니다. ModalControl 을 의도하신 것 같습니다. 이런 이름도 명확하게 쓰는 연습이 필요합니다. 추후에 다른 개발자와 협력할 경우 이런 부분에서 혼란을 일으킬 수 잇기 떄문입니다.

**Comment by DevelopSoo** [comment]
<img width="276" alt="스크린샷 2023-06-30 오후 6 03 43" src="https://github.com/hgyeom/Sparta_coding_club/assets/69490984/9101d34a-a389-462a-839b-4058ac03751b">

버튼옆에 이미지가 깨집니다. 이는 다른 사람이 접근할 수 없는 이미지 주소이기 때문입니다.

**Comment by hgyeom** [comment]
넵 다음부터는 새로운 레파지토리를 사용하도록 하겠습니다 .  마우스 다운 같은 경우는 click과 차이점을 시험해보다가 그대로 제출한 것 같습니다. 뭔가 필요성이 있어서 사용한 것은 아닙니다. 함수명 같은 경우도 조금 더 생각하고 확인하고 짓도록 하겠습니다. 다음 과제부터는 문서를 더 꼼꼼히 읽어서 필수 구현 사항을 확실하게 숙지하도록 하겠습니다. 피드백 감사합니다!
